# Generated by Django 6.0 on 2026-01-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='attacklog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='attacklog',
            name='action_taken',
            field=models.CharField(choices=[('NONE', 'No action taken'), ('BLOCKED', 'IP Blocked'), ('SESSION_REVOKED', 'Session Revoked'), ('REVIEWED', 'Reviewed by admin'), ('AUTO_BLOCKED', 'Automatically Blocked')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='recommended_action',
            field=models.TextField(default='Review and investigate this attack'),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='reverse_action',
            field=models.TextField(default='No action to reverse'),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20),
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('blocked_by', models.CharField(default='admin', max_length=100)),
                ('is_permanent', models.BooleanField(default=False)),
                ('unblock_at', models.DateTimeField(blank=True, null=True)),
                ('related_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.attacklog')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-blocked_at'],
            },
        ),
    ]
